export const TOGGLE_TIMER_30S = 'TOGGLE_TIMER_30S';
export const TOGGLE_TIMER_1MIN = 'TOGGLE_TIMER_1MIN';
export const TOGGLE_TIMER_2MIN = 'TOGGLE_TIMER_2MIN';
export const TOGGLE_TIMER_30S_15S = 'TOGGLE_TIMER_30S_15S';
